const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const PALETTE=['#ba92ff','#7b55da','#ece0ff','#594170','#ca85bb','#91bbbf'];
const euro=n=>new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR',maximumFractionDigits:2}).format(n||0);
const attrs=(kind,key,tip)=>`data-chart="${esc(kind)}" data-key="${esc(key)}" data-tip="${esc(tip)}" tabindex="0" role="button" aria-label="${esc(tip)}. Open details"`;
export function timeline(rows,metric='gross_mrr'){
 if(!rows.length)return '<div class="chart-empty"><span>01 / START RECORDING</span><h3>Your next chapter<br>starts here.</h3><p>Real monthly snapshots will build this graph. No historical estimates are substituted.</p></div>';
 const W=1000,H=310,L=55,R=24,T=30,B=50,max=Math.max(1,...rows.map(r=>Number(r[metric])||0))*1.2,plotW=W-L-R,plotH=H-T-B;
 const points=rows.map((r,i)=>({r,x:L+(rows.length===1?plotW/2:i*plotW/(rows.length-1)),y:T+plotH-(Number(r[metric])||0)/max*plotH}));
 const line=points.map((p,i)=>(i?'L':'M')+p.x+','+p.y).join(' '),value=v=>metric==='active_members'?String(Math.round(v)):metric==='churn_rate'?Number(v||0).toFixed(1)+'%':euro(v);
 return `<svg class="history-svg" viewBox="0 0 ${W} ${H}" role="group" aria-label="Recorded monthly ${metric==='active_members'?'active members':metric==='estimated_net'?'estimated net MRR':metric==='churn_rate'?'member churn rate':'gross MRR'}"><defs><linearGradient id="history-fill" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#ab7bea" stop-opacity=".33"/><stop offset="1" stop-color="#ab7bea" stop-opacity="0"/></linearGradient></defs>${[0,1,2,3].map(i=>{const y=T+plotH*i/3;return `<line x1="${L}" x2="${W-R}" y1="${y}" y2="${y}" class="chart-grid"/><text x="0" y="${y+4}" class="chart-axis">${esc(value(max*(1-i/3)))}</text>`}).join('')}${points.length>1?`<path d="${line} L${points.at(-1).x},${T+plotH} L${points[0].x},${T+plotH} Z" fill="url(#history-fill)"/><path d="${line}" fill="none" stroke="#bb96f3" stroke-width="3"/>`:''}${points.map(p=>`<g ${attrs('month',p.r.month,p.r.month+' · '+value(p.r[metric])+' · '+p.r.active_members+' active members')}><rect x="${p.x-18}" y="${T}" width="36" height="${plotH}" fill="transparent"/><line class="chart-crosshair" x1="${p.x}" x2="${p.x}" y1="${T}" y2="${T+plotH}"/><circle cx="${p.x}" cy="${p.y}" r="5" fill="#d8bdff" stroke="#251734" stroke-width="3"/><text x="${p.x}" y="${H-14}" text-anchor="middle" class="chart-axis">${p.r.month}</text><title>${esc(p.r.month+' · '+value(p.r[metric]))}</title></g>`).join('')}</svg>${rows.length===1?'<p class="chart-note">One recorded month so far. The line grows as real snapshots accumulate.</p>':''}`;
}
export function ring(rows,total,label,kind='tier'){
 const sum=rows.reduce((s,r)=>s+r.value,0),r=90,c=2*Math.PI*r;let offset=0;
 return `<div class="ring-layout"><svg class="ring-svg" viewBox="0 0 250 250" role="group" aria-label="${esc(label)}"><circle cx="125" cy="125" r="90" fill="none" stroke="#ffffff08" stroke-width="24"/>${rows.map((row,i)=>{const length=sum?row.value/sum*c:0,start=offset;offset+=length;return length?`<circle ${attrs(kind,row.key,row.label+' · '+euro(row.value)+' · '+Math.round(row.value/sum*100)+(kind==='tier'?'% of MRR':'% of cash received'))} cx="125" cy="125" r="90" fill="none" stroke="${PALETTE[i%6]}" stroke-width="24" stroke-dasharray="${Math.max(0,length-4)} ${c}" stroke-dashoffset="${-start}" transform="rotate(-90 125 125)"/>`:''}).join('')}<text x="125" y="124" text-anchor="middle" class="ring-total">${esc(total)}</text><text x="125" y="147" text-anchor="middle" class="chart-axis ring-caption">${esc(label)}</text></svg><div class="chart-legend">${rows.map((row,i)=>`<button ${attrs(kind,row.key,row.label+' · '+euro(row.value))}><i style="background:${PALETTE[i%6]}"></i><span>${esc(row.label)}<small>${kind==='tier'?(row.count??0)+' members':'Recorded cash'}</small></span><strong>${euro(row.value)}</strong></button>`).join('')}</div></div>`;
}
export function columns(rows,{kind='country',money=true}={}){const max=Math.max(1,...rows.map(r=>r.value));return `<div class="column-chart">${rows.map((r,i)=>`<button class="chart-column" ${attrs(kind,r.key,r.label+' · '+(money?euro(r.value):r.value)+' · '+(r.detail||''))}><span class="column-value">${money?euro(r.value):r.value}</span><span class="column-track"><i style="height:${Math.max(0,r.value/max*100)}%;background:${PALETTE[i%6]}"></i></span><span class="column-label">${esc(r.label)}</span></button>`).join('')}</div>`;}
export function movement(events){const keys=['new','expansion','contraction','churn'],labels=['New members','Upgrades','Downgrades','Cancellations'],rows=keys.map((k,i)=>({key:k,label:labels[i],value:events.filter(e=>e.category===k).reduce((s,e)=>s+Number(e.delta),0),count:events.filter(e=>e.category===k).length})),max=Math.max(1,...rows.map(r=>Math.abs(r.value)));return `<div class="movement-chart">${rows.map(r=>`<button ${attrs('movement',r.key,r.label+' · '+euro(r.value)+' · '+r.count+' observed changes')} class="movement-column"><span class="movement-value ${r.value<0?'negative':'positive'}">${r.value>0?'+':''}${euro(r.value)}</span><div class="movement-track"><i class="${r.value<0?'down':'up'}" style="height:${Math.max(0,Math.abs(r.value)/max*90)}px"></i></div><strong>${r.label}</strong><small>${r.count} changes</small></button>`).join('')}</div>`;}

// All saved monthly observations. Missing months stay gaps rather than invented values.
export function membershipHistory(snapshots){
 const rows=[...snapshots].filter(r=>/^\d{4}-\d{2}$/.test(r.month)).sort((a,b)=>a.month.localeCompare(b.month));
 if(!rows.length)return '<div class="chart-empty"><h3>Your membership story starts here.</h3><p>No saved membership history yet. Real observations will appear after the dashboard records its first snapshot.</p></div>';
 const value=v=>v==null||v===''||!Number.isFinite(Number(v))?null:Math.max(0,Number(v)),number=v=>value(v)==null?'Not recorded':String(value(v));
 const index=m=>Number(m.slice(0,4))*12+Number(m.slice(5))-1,start=index(rows[0].month),span=index(rows.at(-1).month)-start;
 const W=Math.max(900,(span+1)*82),H=440,L=65,R=35,plot=W-L-R,x=r=>L+(span?(index(r.month)-start)*plot/span:plot/2);
 const peak=Math.max(1,...rows.map(r=>value(r.active_members)||0)),flow=Math.max(1,...rows.flatMap(r=>[value(r.new_members)||0,value(r.cancelled_members)||0]));
 const y=v=>220-(v/peak)*150;let previous=null;
 const segments=rows.map(r=>{const v=value(r.active_members);if(v==null){previous=null;return '';}const p={x:x(r),y:y(v),i:index(r.month)},d=previous&&p.i===previous.i+1?`<path d="M${previous.x},${previous.y} L${p.x},${p.y}" fill="none" stroke="#c995f7" stroke-width="3"/>`:'';previous=p;return d;}).join('');
 return `<div class="membership-chart-scroll" tabindex="0" aria-label="All recorded membership history. Scroll horizontally for more months."><svg class="membership-svg" style="min-width:${W}px" viewBox="0 0 ${W} ${H}" role="group" aria-label="Active members, joins and departures by month"><text x="${L}" y="26" class="membership-axis-title">ACTIVE MEMBERS</text>${[0,.5,1].map(f=>`<line x1="${L}" x2="${W-R}" y1="${y(peak*f)}" y2="${y(peak*f)}" class="chart-grid"/><text x="${L-12}" y="${y(peak*f)+5}" text-anchor="end">${Math.round(peak*f)}</text>`).join('')}${segments}<text x="${L}" y="262" class="membership-axis-title">JOINED / LEFT</text><line x1="${L}" x2="${W-R}" y1="335" y2="335" class="chart-grid"/>${rows.map(r=>{const X=x(r),n=value(r.active_members),joined=value(r.new_members),left=value(r.cancelled_members),tip=r.month+' · '+number(n)+' active · '+number(joined)+' joined · '+number(left)+' left',up=(joined||0)/flow*48,down=(left||0)/flow*48;return `<g ${attrs('membership-month',r.month,tip)}><rect x="${X-30}" y="45" width="60" height="350" fill="transparent"/>${n==null?'':`<circle cx="${X}" cy="${y(n)}" r="6" fill="#dcbaff" stroke="#261334" stroke-width="2"/><text x="${X}" y="${y(n)-14}" text-anchor="middle">${n}</text>`}${joined==null?'':`<rect x="${X-12}" y="${335-up}" width="24" height="${up}" rx="3" fill="#8edac4"/>`}<text x="${X}" y="${335-up-9}" text-anchor="middle" fill="#8edac4">${joined==null?'—':'+'+joined}</text>${left==null?'':`<rect x="${X-12}" y="335" width="24" height="${down}" rx="3" fill="#ed98bd"/>`}<text x="${X}" y="${335+down+18}" text-anchor="middle" fill="#ed98bd">${left==null?'—':'−'+left}</text><text x="${X}" y="420" text-anchor="middle">${esc(r.month)}</text><title>${esc(tip)}</title></g>`}).join('')}</svg></div><details class="membership-values"><summary>View monthly figures</summary><div class="table-wrap"><table><thead><tr><th>Month</th><th>Active members</th><th>Joined</th><th>Left</th></tr></thead><tbody>${rows.map(r=>`<tr><td><button class="text-action" ${attrs('membership-month',r.month,r.month+' membership details')}>${esc(r.month)}</button></td><td>${number(r.active_members)}</td><td>${number(r.new_members)}</td><td>${number(r.cancelled_members)}</td></tr>`).join('')}</tbody></table></div></details>`;
}
