const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const PALETTE=['#ba92ff','#7b55da','#ece0ff','#594170','#ca85bb','#91bbbf'];
const euro=n=>new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR',maximumFractionDigits:2}).format(n||0);
const attrs=(kind,key,tip)=>`data-chart="${esc(kind)}" data-key="${esc(key)}" data-tip="${esc(tip)}" tabindex="0" role="button" aria-label="${esc(tip)}. Open details"`;
export function timeline(rows,metric='gross_mrr'){
 if(!rows.length)return '<div class="chart-empty"><span>01 / START RECORDING</span><h3>Your next chapter<br>starts here.</h3><p>Real monthly snapshots will build this graph. No historical estimates are substituted.</p></div>';
 const W=1000,H=310,L=55,R=24,T=30,B=50,max=Math.max(1,...rows.map(r=>Number(r[metric])||0))*1.2,plotW=W-L-R,plotH=H-T-B;
 const points=rows.map((r,i)=>({r,x:L+(rows.length===1?plotW/2:i*plotW/(rows.length-1)),y:T+plotH-(Number(r[metric])||0)/max*plotH}));
 const line=points.map((p,i)=>(i?'L':'M')+p.x+','+p.y).join(' '),value=v=>metric==='active_members'?String(Math.round(v)):metric==='churn_rate'?Number(v||0).toFixed(1)+'%':euro(v);
 return `<svg class="history-svg" viewBox="0 0 ${W} ${H}" role="group" aria-label="Recorded monthly ${metric==='active_members'?'active members':metric==='estimated_net'?'estimated net MRR':metric==='churn_rate'?'member churn rate':'gross MRR'}"><defs><linearGradient id="history-fill" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#ab7bea" stop-opacity=".33"/><stop offset="1" stop-color="#ab7bea" stop-opacity="0"/></linearGradient></defs>${[0,1,2,3].map(i=>{const y=T+plotH*i/3;return `<line x1="${L}" x2="${W-R}" y1="${y}" y2="${y}" class="chart-grid"/><text x="0" y="${y+4}" class="chart-axis">${esc(value(max*(1-i/3)))}</text>`}).join('')}${points.length>1?`<path d="${line} L${points.at(-1).x},${T+plotH} L${points[0].x},${T+plotH} Z" fill="url(#history-fill)"/><path d="${line}" fill="none" stroke="#bb96f3" stroke-width="3"/>`:''}${points.map(p=>`<g ${attrs('month',p.r.month,p.r.month+' · '+value(p.r[metric])+' · '+p.r.active_members+' active members')}><rect x="${p.x-18}" y="${T}" width="36" height="${plotH}" fill="transparent"/><line class="chart-crosshair" x1="${p.x}" x2="${p.x}" y1="${T}" y2="${T+plotH}"/><circle cx="${p.x}" cy="${p.y}" r="5" fill="#d8bdff" stroke="#251734" stroke-width="3"/><text x="${p.x}" y="${H-14}" text-anchor="middle" class="chart-axis">${p.r.month}</text><title>${esc(p.r.month+' · '+value(p.r[metric]))}</title></g>`).join('')}</svg>${rows.length===1?'<p class="chart-note">One recorded month so far. The line grows as real snapshots accumulate.</p>':''}`;
}
export function ring(rows,total,label,kind='tier'){
 const sum=rows.reduce((s,r)=>s+r.value,0),r=90,c=2*Math.PI*r;let offset=0;
 return `<div class="ring-layout"><svg class="ring-svg" viewBox="0 0 250 250" role="group" aria-label="${esc(label)}"><circle cx="125" cy="125" r="90" fill="none" stroke="#ffffff08" stroke-width="24"/>${rows.map((row,i)=>{const length=sum?row.value/sum*c:0,start=offset;offset+=length;return length?`<circle ${attrs(kind,row.key,row.label+' · '+euro(row.value)+' · '+Math.round(row.value/sum*100)+(kind==='tier'?'% of MRR':'% of cash received'))} cx="125" cy="125" r="90" fill="none" stroke="${PALETTE[i%6]}" stroke-width="24" stroke-dasharray="${Math.max(0,length-4)} ${c}" stroke-dashoffset="${-start}" transform="rotate(-90 125 125)"/>`:''}).join('')}<text x="125" y="124" text-anchor="middle" class="ring-total">${esc(total)}</text><text x="125" y="147" text-anchor="middle" class="chart-axis ring-caption">${esc(label)}</text></svg><div class="chart-legend">${rows.map((row,i)=>`<button ${attrs(kind,row.key,row.label+' · '+euro(row.value))}><i style="background:${PALETTE[i%6]}"></i><span>${esc(row.label)}<small>${kind==='tier'?(row.count??0)+' members':'Recorded cash'}</small></span><strong>${euro(row.value)}</strong></button>`).join('')}</div></div>`;
}
export function columns(rows,{kind='country',money=true}={}){const max=Math.max(1,...rows.map(r=>r.value));return `<div class="column-chart">${rows.map((r,i)=>`<button class="chart-column" ${attrs(kind,r.key,r.label+' · '+(money?euro(r.value):r.value)+' · '+(r.detail||''))}><span class="column-value">${money?euro(r.value):r.value}</span><span class="column-track"><i style="height:${Math.max(0,r.value/max*100)}%;background:${PALETTE[i%6]}"></i></span><span class="column-label">${esc(r.label)}</span></button>`).join('')}</div>`;}
export function movement(events){const keys=['new','expansion','contraction','churn'],labels=['New members','Upgrades','Downgrades','Cancellations'],rows=keys.map((k,i)=>({key:k,label:labels[i],value:events.filter(e=>e.category===k).reduce((s,e)=>s+Number(e.delta),0),count:events.filter(e=>e.category===k).length})),max=Math.max(1,...rows.map(r=>Math.abs(r.value)));return `<div class="movement-chart">${rows.map(r=>`<button ${attrs('movement',r.key,r.label+' · '+euro(r.value)+' · '+r.count+' observed changes')} class="movement-column"><span class="movement-value ${r.value<0?'negative':'positive'}">${r.value>0?'+':''}${euro(r.value)}</span><div class="movement-track"><i class="${r.value<0?'down':'up'}" style="height:${Math.max(0,Math.abs(r.value)/max*90)}px"></i></div><strong>${r.label}</strong><small>${r.count} changes</small></button>`).join('')}</div>`;}
