// Transcribed from the owner's October schedule; all /05 Premium labels were
// explicitly confirmed by the owner as October 2026. No publication inferred.
export const OCTOBER_GROUPS={
'06':['goncalo_pratas','mr_ammolite','passione_abarth','_marcodanna_','jamierocket','majr_trofeo','ewan.595','andre__mta','_pocket.ferrari_','mr.abarthini'],
'09':['motorsportcourt93','damien.ord','abarthcino595','abarth.hh','grigio_esseesse','__gianmarcooo__','carlos_595_comp','eli_abarth91','shadowtheabarth'],
'12':['miguel_a595','ceccadaniiiiii','tummy_abarth','trackbarth','solla_official_2.0','einfach_nur_mxritz','r4_lbx','green_scorpion_70th','nonameabarth'],
'15':['scrpy595','evo_supersport','reol_rereol3','13thracing','red595abarth','chris_esseesse','abarthsc','abarthdalina','flysquasher'],
'18':['fit_alina94','crazydavid88','emily__coskin','carrosseriespeedrepar47','l16apt','_only595_','595_scorpio_grey','di_f595','abarth.orsche'],
'21':['low_abarth','abarthvero595','c_turismo51','mathias.rowe','monsterabarth','juliane24x7','givs3ppe_99','bee_595_','nerogiallo_595pista'],
'24':['gigi_ab595','giuseppe_abarth','_de.inverso_','manu__595','jean_abarth_695','_zomiii_','_.__paul.__','_.berta595._','abarthrocket'],
'27':['that_grey_abarth12','wizardracing34','sts_abarth','marlks17_','antrabarth','sebabarth64','lele_695esseesse','abarth.ini','goldbarth_595'],
'30':['lm.abarth','_jo99','thatyellowabarth595','zoesabarth','abarth_dom','officialmissnicole']};
export const OCTOBER_SOLOS=[['05','officialmissnicole'],['06','_jo99'],['07','wizardracing34'],['08','lm.abarth'],['09','flysquasher'],['10','fit_alina94'],['11','p31_esc'],['12','carrosseriespeedrepar47'],['13','l16apt'],['14','_only595_'],['16','mathias.rowe'],['17','monsterabarth'],['18','juliane24x7'],['19','gigi_ab595'],['20','manu__595'],['22','jean_abarth_695'],['23','abarthrocket'],['24','abarth.orsche'],['25','that_grey_abarth12'],['26','bestia_grigia'],['28','lm.abarth'],['29','_jo99'],['30','wizardracing34'],['31','officialmissnicole']];
export const normalizeHandle=h=>String(h||'').trim().replace(/^@/,'').toLowerCase();
export function octoberSchedule(members=[]){const find=h=>{const matches=members.filter(m=>normalizeHandle(m.handle)===normalizeHandle(h));return matches.length===1?matches[0]:null;};const occurrences={};const rows=[...Object.entries(OCTOBER_GROUPS).sort(([a],[b])=>a.localeCompare(b)).map(([d,handles])=>({date:'2026-10-'+d,handles,title:'Club carousel · '+d+' October',type:'Basic Club Carousel'})),...OCTOBER_SOLOS.map(([d,h])=>{const occurrence=occurrences[h]=(occurrences[h]||0)+1,m=find(h);return {date:'2026-10-'+d,handles:[h],title:'@'+h+' · Premium feature',type:m?.tier==='Premium+'?'Premium+ Feature '+Math.min(occurrence,2):'Premium Solo'};})];return rows.map((r,i)=>({...r,id:'c6102026-0000-4000-8000-'+String(i+1).padStart(12,'0'),import_key:'owner-october-2026-'+(i+1),member_ids:r.handles.map(find).filter(Boolean).map(m=>String(m.id)),scheduled_handles:r.handles.map(h=>'@'+h),status:'Scheduled',content_ready:false,caption_ready:false,notes:'From your supplied October 2026 schedule. Publication and content readiness have not been confirmed.'}));}
export async function importOctoberSchedule(store){if(store.list('migration').some(r=>r.source==='owner-october-2026'))return 0;const existing=store.list('content');let added=0;for(const row of octoberSchedule(store.members)){if(existing.some(p=>p.id===row.id||p.import_key===row.import_key))continue;const same=existing.find(p=>p.date===row.date&&p.type===row.type&&((p.scheduled_handles||[]).map(normalizeHandle).sort().join('|')===row.handles.map(normalizeHandle).sort().join('|')||(p.member_ids?.length===row.handles.length&&[...p.member_ids].sort().join('|')===[...row.member_ids].sort().join('|'))));if(same){await store.save('content',{...same,import_key:row.import_key,scheduled_handles:row.scheduled_handles},same.id);continue;}const {id,handles,...data}=row;await store.save('content',data,id);added++;}await store.save('migration',{source:'owner-october-2026',imported_at:new Date().toISOString(),posts:33},'c6102026-0000-4000-8001-000000000001');return added;}
