export class Store {
 constructor(client){this.client=client;this.records=[];this.members=[];this.snapshots=[];this.events=[];this.settings={};}
 async rows(table){let all=[];for(let p=0;;p++){const {data,error}=await this.client.from(table).select('*').order(table==='ops_revenue_events'?'occurred_at':table==='ops_snapshots'?'month':'id').range(p*1000,p*1000+999);if(error)throw error;all.push(...data);if(data.length<1000)return all;}}
 async load(){const [members,records,snapshots,events]=await Promise.all(['members','ops_records','ops_snapshots','ops_revenue_events'].map(t=>this.rows(t)));this.members=members;this.records=records;this.snapshots=snapshots;this.events=events;this.settings=this.list('settings')[0]||{};}
 list(kind){return this.records.filter(r=>r.kind===kind).map(r=>({...r.data,id:r.id,version:r.version}));}
 async save(kind,data,id){const old=this.records.find(r=>r.id===id);const payload={...data};delete payload.id;delete payload.version;let q;if(old){q=this.client.from('ops_records').update({data:payload,version:old.version+1}).eq('id',id).eq('version',old.version);}else q=this.client.from('ops_records').insert({id:id||crypto.randomUUID(),kind,data:payload});const {data:rows,error}=await q.select();if(error)throw error;if(!rows?.length)throw Error('This item changed on another device. Refresh before saving.');this.records=this.records.filter(r=>r.id!==rows[0].id).concat(rows);return rows[0].id;}
 async remove(id){const old=this.records.find(r=>r.id===id);if(!old)return;const {data,error}=await this.client.from('ops_records').delete().eq('id',id).eq('version',old.version).select('id');if(error)throw error;if(!data.length)throw Error('This item changed. Refresh and retry.');this.records=this.records.filter(r=>r.id!==id);}
 async member(id,patch){const {data,error}=await this.client.from('members').update(patch).eq('id',id).select();if(error)throw error;if(!data.length)throw Error('Member was not saved.');this.members=this.members.map(m=>String(m.id)===String(id)?data[0]:m);}
 async snapshot(){const {error}=await this.client.rpc('ops_capture_snapshot');if(error)throw error;this.snapshots=await this.rows('ops_snapshots');this.events=await this.rows('ops_revenue_events');}
}
